// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9J7wNfL0oPxPRnGq330C7yXcZ12kOneE',
    appId: '1:720466991073:web:828bffe5406b8d6d28e4a0',
    messagingSenderId: '720466991073',
    projectId: 'rentmitra-babbd',
    authDomain: 'rentmitra-babbd.firebaseapp.com',
    storageBucket: 'rentmitra-babbd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9S1jDYW0S1hN54XfbJM9OvP1FLZm5f2Q',
    appId: '1:720466991073:android:ce1eac1dabcf7c3728e4a0',
    messagingSenderId: '720466991073',
    projectId: 'rentmitra-babbd',
    storageBucket: 'rentmitra-babbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-qOkGGKtPBAQa3U74UfZJSAETLgGuoD8',
    appId: '1:720466991073:ios:6af336c85d435e4e28e4a0',
    messagingSenderId: '720466991073',
    projectId: 'rentmitra-babbd',
    storageBucket: 'rentmitra-babbd.firebasestorage.app',
    iosBundleId: 'com.rentmitra.rentmitraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-qOkGGKtPBAQa3U74UfZJSAETLgGuoD8',
    appId: '1:720466991073:ios:6af336c85d435e4e28e4a0',
    messagingSenderId: '720466991073',
    projectId: 'rentmitra-babbd',
    storageBucket: 'rentmitra-babbd.firebasestorage.app',
    iosBundleId: 'com.rentmitra.rentmitraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9J7wNfL0oPxPRnGq330C7yXcZ12kOneE',
    appId: '1:720466991073:web:df18a3c48764058c28e4a0',
    messagingSenderId: '720466991073',
    projectId: 'rentmitra-babbd',
    authDomain: 'rentmitra-babbd.firebaseapp.com',
    storageBucket: 'rentmitra-babbd.firebasestorage.app',
  );
}
